<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StickmanFight.Reliable.Reliability</RootNamespace>
    <AssemblyName>StickmanFight.Reliability</AssemblyName>
  </PropertyGroup>

</Project>
